// Generates packages/sim/src/trig-table.ts: a quarter-wave sine table with
// 1,025 entries (index i is the angle i / 4096 of a turn), scaled by 2^16.
// The sim may not call Math.sin, so the table is computed here once, rounded
// to integers and committed as literals. Run: pnpm --filter @blockyrts/tools gen:trig
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const QUARTER = 1024;
const values: number[] = [];
for (let i = 0; i <= QUARTER; i++) {
  values.push(Math.round(Math.sin((i / (QUARTER * 4)) * 2 * Math.PI) * 65536));
}

const lines: string[] = [];
for (let i = 0; i < values.length; i += 16) {
  lines.push('  ' + values.slice(i, i + 16).join(', ') + ',');
}

const out = `// Generated by packages/tools/scripts/gen-trig-table.ts. Do not edit by hand.
// Quarter-wave sine: SIN_QUARTER[i] = round(sin(i / 4096 turn) * 65536), i = 0..1024.
export const SIN_QUARTER: Int32Array = Int32Array.from([
${lines.join('\n')}
]);
`;

const target = fileURLToPath(new URL('../../sim/src/trig-table.ts', import.meta.url));
writeFileSync(target, out);
console.log(`wrote ${values.length} entries to ${target}`);
