// How to Play's plain words: the balance catalog names a number after the
// code's own name for it ("Calm after s", "Half width", "Breed steps"),
// which reads well to whoever tunes the game and puzzles a player. This
// pass, run on How to Play's own copy of the catalog, gives those numbers a
// name in plain words, the unit they are really in (seconds, metres), the
// page of names they point at, and leaves out the few that are only the
// code's bookkeeping. The balance editor keeps its own names.
import { WU_PER_COLUMN, WU_PER_TERRAIN_UNIT } from '@blockyrts/sim';
import type { Catalog, CatNode, FieldNode, UnitId } from '@blockyrts/balance';

type RefKind = NonNullable<FieldNode['ref']>;

interface Fix {
  label?: string;
  unit?: UnitId;
  /** Multiplies the number before it is shown in `unit` (terrain units and columns to world units). */
  times?: number;
  ref?: RefKind;
}

/** Terrain units (11.25 cm) shown in metres. */
const TU: Fix = { unit: 'metresWu', times: WU_PER_TERRAIN_UNIT };
/** Columns (45 cm) shown in metres. */
const COL: Fix = { unit: 'metresWu', times: WU_PER_COLUMN };
const S: Fix = { unit: 'wholeSeconds' };
const M: Fix = { unit: 'metres' };
const PCT: Fix = { unit: 'percent' };
const lab = (label: string, more: Fix = {}): Fix => ({ ...more, label });

/** By the label the catalog gave, wherever it shows. */
const BY_LABEL: Readonly<Record<string, Fix>> = {
  // Times.
  'Breed steps': lab('Has young every'),
  'Burn steps': lab('Burns a food every'),
  'Cast steps': lab('Casting time'),
  'Clip steps': lab('Leap takes'),
  'Crouch steps': lab('Crouches for'),
  'Flight steps': lab('In the air for'),
  'Held steps': lab('Holds its prey for'),
  'Hold steps': lab('Holds for'),
  'Low steps': lab('Flies low for'),
  'Rite steps': lab('Rite takes'),
  'Roar steps': lab('Roars for'),
  'Wake every steps': lab('Looks round every'),
  'Worship steps': lab('Worships for'),
  'Wings drain over': lab('Drains over'),
  'Calm after s': lab('Calms down after', S),
  'Chase line s': lab('Says a chasing line every', S),
  'Every s': lab('Every', S),
  'Fish s': lab('Fishing takes', S),
  'Greet gap s': lab('Greets again after', S),
  'Hold s': lab('Holds for', S),
  'Last s': lab('Lasts', S),
  'Pick s': lab('Picking takes', S),
  'Plant walk s': lab('Gives up on a spot after', S),
  'Remark s': lab('Remarks about every', S),
  'Rest s': lab('Rests for', S),
  'Rite s': lab('Rite every', S),
  'Spring fight line s': lab('Fighting, speaks every', S),
  'Spring warn line s': lab('Warning, speaks every', S),
  'Sworn after s': lab('Sworn to you after fighting for', S),
  'Train s': lab('Hiring takes', S),
  'Vanish every s': lab('Vanishes every', S),
  'Vanish s': lab('Stays unseen for', S),
  'Warn gap s': lab('Warns again after', S),
  'Watch s': lab('Watches for', S),
  'Worship every s': lab('Worships about every', S),
  'Burn seconds': lab('Burns for', S),
  'Max s': lab('At most every', S),
  'Min s': lab('At least every', S),
  'Every days': lab('Every (days)'),
  'Every nights': lab('Again after (nights)'),
  'Blessed every nights': lab('Bright Night once in (nights)'),
  'Idol area every nights': lab('Bright area again after (nights)'),
  'Idol use every nights': lab('Usable again after (nights)'),
  'Hawthorne grow nights': lab('A Sweet Hawthorne grows in (nights)'),
  'Hawthorne regrow days': lab('Fruit grows back in (days)'),
  'Boss return nights': lab('Returns after a defeat (nights)'),
  'Fog from night': lab('Fog nights from night'),
  'Ledger minutes': lab('Food line covers the last (minutes)'),
  Cycle: lab('A whole day'),
  Hex: lab('Stumble hex lasts'),
  Engulf: lab('Engulfs a worker for'),
  Fuse: lab('Fuse burns for'),
  Insult: lab('An insult closes trade for'),
  Meal: lab('Meals every'),
  Eat: lab('Eating takes'),
  Bandage: lab('A bandage heals over'),
  Plant: lab('Planting takes'),
  Prospect: lab('Prospecting takes'),
  'Prospect hammer': lab('Prospecting with a hammer takes'),
  Rebuild: lab('Rebuilds a hut every'),
  Regrow: lab('Gains back a person every'),
  Relight: lab('Relighting takes'),
  Slaughter: lab('Slaughter takes'),
  Young: lab('The young grow up in'),
  'Mage train': lab('Training a mage takes'),
  'Worker train': lab('Training a worker takes'),
  'Heal after': lab('Starts healing after a fight by'),
  'Heal every': lab('Heals 1 health every'),
  'Health tick': lab('Healing and starving come every'),
  'Leave after': lab('Leaves after'),
  'Merc refill': lab('Mercenaries come back every'),
  'Caravan every': lab('A caravan every'),
  'Dwarf raid every': lab('Dwarves at war raid every'),
  'Elf raid every': lab('Elves at war raid every'),
  'Dwarf rebuild': lab('Migrated Dwarves rebuild for'),
  'Quest ask again': lab('After a No, asked again in'),
  'Quest repeat': lab('Offered again after a claim'),
  'Question wait': lab('A question waits for an answer for'),
  'Make ask min': lab('Workshop offers at most every'),
  'First kit ask': lab('No asks for better kit before'),
  'Hurt ask quiet': lab('A hurt unit asks to eat after a quiet'),
  'Safe quiet': lab('"I feel safe" again after a quiet'),
  'Tree warn gap': lab('Tree warnings at most every'),
  'Tribe give up': lab('Tribes give up a chase after'),
  'Raid after dawn': lab('Raids march out after dawn by'),
  'Cleared wait': lab('No new lair at a cleared site for'),
  'Lair share delay': lab("A lair's share comes out after"),
  'Kill share window': lab('Hitters share a kill within'),
  'Combat pause': lab('Mana stops refilling in combat for'),
  'Loot keep': lab('Loot left on the ground lasts'),
  'Loot talk gap': lab('Units talk about loot at most every'),
  'Wild aggro': lab('Goes for prey it could reach within'),
  'Wild check': lab('Wild patches checked every'),
  'Wild provoked': lab('Fights back at what hurt it within'),
  'Wild rest max': lab('Rests at most'),
  'Wild rest min': lab('Rests at least'),
  'Hawthorne fell': lab('Cutting down a Sweet Hawthorne takes'),
  'Farm harvest': lab('A harvest takes'),
  'Starve harm after': lab('Starving harms after'),
  'Smoulder time': lab('Smoulders for'),
  'Hop': lab('A hop up or down takes'),
  Cast: lab('Casting time'),
  // Distances.
  'Gather m': lab('Gathers within', M),
  'Greet m': lab('Greets units within', M),
  'Grounds m': lab('Its grounds reach', M),
  'Grudge m': lab('Goes for those who wronged it within', M),
  'Hover m': lab('Hovers within', M),
  'Leash m': lab('Chases no farther than', M),
  'Max m': lab('At most', M),
  'Min m': lab('At least', M),
  'Peak m': lab('Leaps as high as', M),
  'Plant max m': lab('Plants at most this far out', M),
  'Plant min m': lab('Plants at least this far out', M),
  'Radius m': lab('Radius', M),
  'Revel m': lab('Revels within', M),
  'Ring m': lab('Stand round him at', M),
  'Ring max m': lab('Waves come out at most', M),
  'Ring min m': lab('Waves come out at least', M),
  'Rite m': lab('Rite reaches', M),
  'Seek m': lab('Seeks within', M),
  'Sight m': lab('Sees', M),
  'Spread m': lab('Spreads', M),
  'Village m': lab('Village within', M),
  'Wake m': lab('Wakes when a unit comes within', M),
  'War sight m': lab('At war, fights units within', M),
  'Warn m': lab('Warns units within', M),
  'Worship near m': lab('Worships while units are within', M),
  M: lab('Reach', M),
  Apart: lab('Kept apart from other villages by'),
  Chase: lab('Chases up to'),
  'Hunt wu': lab('Hunts within'),
  'Lone wu': lab('Picks off a unit alone within'),
  'Seen wu': lab('Seen within'),
  'Knock wu': lab('Knocks units back'),
  Defend: lab('Defends within'),
  'Keep away': lab('Keeps away from you by'),
  Wander: lab('Wanders up to'),
  'Speech near': lab('Its words reach you within'),
  'Trade range': lab('Trade within'),
  'Raid from': lab('Raiders come in from'),
  'Leave distance': lab('Leaving people vanish at'),
  'Caravan from': lab('A caravan comes in from'),
  'Caravan stop': lab('A caravan stops this far from your base'),
  'Camp radius': lab('A camp is this wide (radius)'),
  'Cleared radius': lab('No new lair within'),
  'Hut ring': lab('Huts stand this far out'),
  'Stake ring': lab('The stake ring stands this far out'),
  'Village aggro': lab('Goblins attack within'),
  'Village chase': lab('Goblins chase up to'),
  'Lair aggro': lab('Residents wake to what comes within'),
  'Lair claim gap': lab('Lairs keep from claimed land by'),
  'Lair gap': lab('Lairs keep apart by'),
  'Lair leash': lab('Residents chase up to'),
  'Lair unit gap': lab('Lairs keep from your units by'),
  'Lair clear radius': lab('Warriors within this share a lair clear'),
  'Tribe keep away': lab('Bands come out at least this far from you'),
  'Tribe sight': lab('Tribes see'),
  'Tribe spawn range': lab('Bands come out within'),
  'Rift seen': lab('Rifts are seen at night from'),
  'Tree warn': lab('Elves see trees felled within'),
  'Crew guard': lab('Crew fight foes within'),
  'Crew reach': lab('Crew stand within'),
  'Haul reach': lab('A hitched animal hauls within'),
  'Engine sight': lab('Engines see'),
  'Charge close': lab('Reining in this close keeps the charge'),
  Far: lab('Knocked back far'),
  Near: lab('Knocked back near'),
  'Extra reach mounted': lab('Extra reach on a mount'),
  'Over wall reach': lab('Reach that stabs over a wall'),
  'Top strike': lab('Flyers strike men up top within'),
  'Up top foe': lab('Men up top fight foes within'),
  'Idle acquire': lab('Idle units fight back within'),
  'Ranged min': lab('Closer than this, fights in melee'),
  Leash: lab('Chases a target it picked up to'),
  'Mage leash': lab('A mage chases up to'),
  'Hunt leash': lab('Without a base, hunts reach'),
  'Fly height': lab('Flies this high'),
  'High fly height': lab('High flyers circle this high'),
  'Swoop height': lab('Swoops down to'),
  'Hand height': lab('Shots leave the hand at'),
  'Staff splash within': lab('Staff splash reaches'),
  'Wings drain within': lab('Drains within'),
  'Breaks that building within': lab('Breaks a building it was shot from within'),
  'Near enough to leave be': lab('Close enough to leave be'),
  Flee: lab('Workers flee this far'),
  'Auto drop': lab('Hands in what it carries within'),
  'Auto repair': lab('Autorepair reaches'),
  'Guard help': lab('Idle fighters help a worker within'),
  'Node search': lab('Looks for another node within'),
  'Repair call': lab('Repair all calls workers within'),
  'Repair search': lab('Repair looks for damage within'),
  'Speak for': lab('Asks for units standing within'),
  'Forage dark': lab('Goes into unseen land up to'),
  'Forage turn': lab('Each sixth of a turn round the base counts as'),
  'Gather switch': lab('Moves on to other nodes within'),
  'Home slack': lab('Home means within'),
  'Loot claim': lab('Goes back for its loot from'),
  'Loot dark': lab('At night picks up loot only within'),
  'Loot hand': lab('Drops go straight into the bag within'),
  'Loot notice': lab('Idle units pick up loot within'),
  'Loot reach': lab('Picks up everything within'),
  'Loot safe': lab('Safe to fetch loot with no enemy within'),
  'Spring warn': lab('Grumbles at units within'),
  'Wild aggro min': lab('Goes for prey within'),
  'Wild assist': lab('Its group joins its fight within'),
  'Wild claim gap': lab('Wild spots keep from claimed land by'),
  'Wild give up': lab('Gives up prey this far beyond its reach'),
  'Wild leash': lab('Strays no farther from its spot than'),
  'Wild patch size': lab('Wild patches are this wide'),
  'Wild roam': lab('Strolls up to'),
  'Wild sleep': lab('Patches empty when no unit comes within'),
  'Wild unit gap': lab('Wanderers come out at least this far from units'),
  'Wild village gap': lab('Wanderers keep from villages by'),
  'Wild wake': lab('Patches fill when a unit comes within'),
  'Claim standoff': lab('Night spawns keep from claimed land by'),
  'Unit standoff': lab('Night spawns keep from units by'),
  'Building claim': lab('A building claims land round it'),
  'Claimed radius': lab('Claims land round it'),
  'Light radius': lab('Lights up round it'),
  Outlying: lab('Lights farther than this from a base count as outlying'),
  'Pan flute radius': lab('Pan flute calls animals within'),
  'Pan flute stop': lab('Called animals stop this near your base'),
  'Chest ring': lab('Chests stand this far from the middle'),
  'Circle spacing': lab('Circles stand at least this far apart'),
  Clearing: lab('The clearing reaches'),
  'Clearing trees max': lab('Clearing trees stand at most'),
  'Clearing trees min': lab('Clearing trees stand at least'),
  'Ruin clear': lab('Nothing else grows within'),
  'Idol area': lab('Bright area round the idol'),
  'Seed spacing': lab('Seeds take root this far apart'),
  'Band blend': lab('Bands blend into each other over'),
  'Band wander': lab("A band's edge wanders up to"),
  'Band width max': lab('Bands are at most this wide'),
  'Band width min': lab('Bands are at least this wide'),
  'Base gap max': lab('Bases stand at most this far apart'),
  'Base gap min': lab('Bases stand at least this far apart'),
  'Boulder base clear': lab('No boulders within this of a base'),
  'Hill blend': lab('Hills blend in over'),
  'Hill site clear': lab('Flat ground round each village site'),
  'Hill start clear': lab('No hills within this of a start'),
  'Landmark distance': lab('The landmark hill stands this far out'),
  'Landmark peak max': lab('The landmark is at most this high'),
  'Landmark peak min': lab('The landmark is at least this high'),
  'Landmark radius': lab("The landmark's foot is this wide (radius)"),
  'Flax field radius': lab('Flax fields are this wide (radius)'),
  // Terrain units and columns.
  'Clamber units': lab('A person clambers up', TU),
  Clamber: lab('Jumps up', TU),
  'Dig limit units': lab('Digs down at most', TU),
  'Dig up max units': lab('Digs up at most', TU),
  'Drop units': lab('Steps down at most', TU),
  Drop: lab('Steps down at most', TU),
  Jump: lab('Jumps up', TU),
  Climb: lab('Climbs', TU),
  'Headroom units': lab('Headroom a person needs', TU),
  'Hill height units': lab('Hills are this high', TU),
  'Level tolerance units': lab('Ground may rise or fall under a building by', TU),
  'Lowland knee units': lab('Low land eases off below', TU),
  'Mob jump units': lab('Monsters jump', TU),
  'Natural floor units': lab('Nothing natural lies deeper than', TU),
  'Reach up units': lab('Builders dig up to', TU),
  'Spread units': lab('A digger takes its column down', TU),
  'Step units': lab('Walks up at full speed', TU),
  'Tunnel height units': lab('A new tunnel is this high', TU),
  'Tunnel max units': lab('Tunnel roofs at most', TU),
  'Tunnel min units': lab('Tunnel roofs at least', TU),
  'Wade units': lab('Wades through water up to', TU),
  'Boulder half': lab('Boulders are this wide', { unit: 'metresWu', times: 2 * WU_PER_COLUMN }),
  'Node search columns': lab('Looks for another node within', COL),
  'Pocket blend columns': lab('A pocket blends back over', COL),
  'Pocket flat columns': lab('A pocket is flat within', COL),
  'Site max columns': lab('A dig box is at most this wide', COL),
  'Tunnel stretch max columns': lab('A stretch of tunnel runs at most', COL),
  'Tunnel width columns': lab('A tunnel is this wide', COL),
  'Wall stretch max columns': lab('A stretch of wall runs at most', COL),
  'World edge columns': lab('The world reaches', COL),
  W: lab('Width', COL),
  D: lab('Depth', COL),
  // Shares and percents.
  'Below pct': lab('Below this share of its health', PCT),
  'Faster pct': lab('Faster by'),
  'Rite pct': lab('Holds the rite to this share of its health'),
  Pct: lab('Chance', PCT),
  'Gem pm': lab('Chance of a gem'),
  'Grave pm': lab('Chance of Touch of the Grave'),
  'Spread pm': lab('Spreads to'),
  'Max rise bp': lab('Arcs up at most'),
  'Pace bp': lab('Pace'),
  'Run bp': lab('Raging, runs at'),
  'Vs wood bp': lab('Against wood'),
  'Hop slow': lab('Slowed while hopping up by'),
  'Hex slow': lab('Stumble hex slows by'),
  'Foot walk': lab('Units on foot walk at'),
  'Artillery pace': lab('Engines move at'),
  'Run speed': lab('A mount runs at'),
  'Run bonus': lab('Running is faster by'),
  'Climb slow': lab('Climbing is this many times slower'),
  'Starving slow': lab('Starving units are slower by'),
  'Climbing damage': lab('Climbers take this much damage on a wall'),
  'Cancel refund': lab('Cancelling refunds'),
  'Armour cap': lab('Armour adds up to at most'),
  'Shelter loss': lab('Losing a shelter costs those inside'),
  'Heal': lab('Heals each time'),
  'Starve harm': lab('Starving harms each time'),
  'Bandage heal': lab('A bandage heals'),
  'Remedy heal': lab('A remedy heals'),
  'Barn hunger': lab('An unfed Barn animal loses'),
  'Hurt ask': lab('Asks to eat at or below'),
  'Home path': lab('Turns home at dusk from no farther than'),
  'Boulder chunk': lab('Chance of a boulder in a stretch of land'),
  'Hot spring chunk': lab('Chance of a hot spring in a stretch of land'),
  'Cliff mountain': lab('Cliffs that become mountains'),
  'Deepwoods iron rock': lab('Iron rock in the Deepwoods, against the Fringe'),
  'Heartland trees': lab('Trees in the Heartland, against the Fringe'),
  'Ring scale': lab('Bands are scaled to'),
  'Forage empty': lab('A material you have none of counts'),
  'Forage need floor': lab('A material counts at least'),
  'Upgrade min time': lab('An upgrade takes at least'),
  Slow: lab('Slows by'),
  'Lean pay': lab('Pays for what it lacks'),
  'Lean sell': lab('Sells what it has plenty of at'),
  'Bundle min': lab('Each bundle is worth at least'),
  'Hunt home': lab('Takes its bag home when this full'),
  'Loot brag': lab('Brags about a find worth'),
  'Loot rare': lab('Rare finds: drops this rare or rarer'),
  'Loot talk': lab('Talks about its loot'),
  Restock: lab('Stock refills each day'),
  'Raid share': lab('At war, fighters that march out'),
  'Surrender dead': lab('Offers to surrender after losing'),
  'Standing max': lab('Standing stones: at most'),
  'Standing min': lab('Standing stones: at least'),
  'Wild horde max': lab('Chance of a group: at most'),
  'Wild horde per night': lab('Chance of a group grows each night by'),
  // Counts and the rest.
  'Ambush mul': lab('Ambush damage times'),
  'Bow spread times': lab('Bow spread on a mount, times'),
  'Dig speed times': lab('Digging is this many times faster'),
  'Fireball wood multiplier': lab('Fireball against wood, times'),
  'Special trinket multiplier': lab('Special trinkets are worth, times'),
  'Bear cap': lab('Bears in the world, at most'),
  'Merc max': lab('Mercenaries for hire, at most'),
  'Merc min': lab('Mercenaries for hire, at least'),
  'Raid band': lab('A Dwarf raid band'),
  'Raid min': lab('At war, at least this many march'),
  'War kills': lab('War after this many kills'),
  'Tree warnings': lab('Tree warnings before war'),
  'Mood declines': lab('Turned-down offers before they sulk'),
  'Offer slots': lab('Goods in one offer, at most'),
  'Silver per gold': lab('Silver to a gold ingot'),
  'Over silver': lab('A mixed payment may go over by (silver)'),
  'Food per silver': lab('Food burned for a silver ingot'),
  Places: lab('Decimal places on the till'),
  'Meal food': lab('Food he eats a meal'),
  'Gift gold': lab('Gift: gold ingots'),
  'Gift roses': lab('Gift: Moon Roses'),
  'Gift silver': lab('Gift: silver ingots'),
  'Roses per bush': lab('Moon Roses a bush grows each Bright Night'),
  'Chest slots': lab('Spaces in a chest'),
  'Pan flute uses': lab('Uses of a pan flute'),
  'Hawthorne fruit': lab('Fruit from a Sweet Hawthorne'),
  'Hawthorne lumber': lab('Lumber from a Sweet Hawthorne'),
  'Hawthorne every': lab('Plants a Sweet Hawthorne every (visits)'),
  'Plant max': lab('Sweet Hawthornes he plants, at most'),
  'Circles per band max': lab('Stone circles in a band, at most'),
  Trilithons: lab('Trilithons in the ring'),
  Necromancers: lab('Necromancers he commands'),
  Floor: lab('At least this many'),
  'Crystals max': lab('Mana crystals, at most'),
  'Crystals min': lab('Mana crystals, at least'),
  'Food max': lab('Food, at most'),
  'Food min': lab('Food, at least'),
  'Gear max': lab('Gear, at most'),
  'Gear min': lab('Gear, at least'),
  'Gear high': lab('Gear: highest tier'),
  'Gear low': lab('Gear: lowest tier'),
  'Gold max': lab('Gold ingots, at most'),
  'Silver max': lab('Silver ingots, at most'),
  'Silver min': lab('Silver ingots, at least'),
  'Trinkets max': lab('Trinkets, at most'),
  'Trinkets min': lab('Trinkets, at least'),
  'Weapons max': lab('Weapons, at most'),
  'Weapons min': lab('Weapons, at least'),
  'Weapon high': lab('Weapons: highest tier'),
  'Weapon low': lab('Weapons: lowest tier'),
  'Armour max': lab('Armour, at most'),
  'Armour min': lab('Armour, at least'),
  'Armour high': lab('Armour: highest tier'),
  'Armour low': lab('Armour: lowest tier'),
  Regen: lab('Heals a second'),
  'Regen off bog': lab('Heals a second off the bog'),
  'Regen on bog': lab('Heals a second on the bog'),
  Wine: lab('Enchanted wine'),
  'Wine mana': lab('Enchanted wine refills mana'),
  Large: lab('Bluestone from a large stone'),
  Small: lab('Bluestone from a small stone'),
  'Flax field max': lab('Plants in a flax field, at most'),
  'Flax field min': lab('Plants in a flax field, at least'),
  'Flax field max trees': lab('Trees near a flax field, at most'),
  'Flax tall one in': lab('One flax plant in this many is tall'),
  'Mushroom trees': lab('Trees for each edible mushroom'),
  'Mushrooms max': lab('Edible mushrooms in a stretch of land, at most'),
  'Mountain gold per 10000': lab('Gold on mountain slopes, per 10,000 spots'),
  'Mountain silver per 10000': lab('Silver on mountain slopes, per 10,000 spots'),
  'Clearing softwood max': lab('Softwood trees in the clearing, at most'),
  'Huts per wolf rider': lab('Huts for each wolf rider'),
  'Wolf pen huts': lab('Huts before a village has a wolf pen'),
  'Tribe cap per player': lab('Tribesmen in the world per player, at most'),
  'Grey asks max': lab('Questions one click answers, at most'),
  'Grey depth': lab('How far back a greyed button looks for causes'),
  'Open questions per player': lab('Open questions at once, per player'),
  'Research facility cap': lab('Research buildings, at most'),
  'Queue limit': lab('Units queued at a building, at most'),
  'Shaft stock limit': lab('A shaft keeps at most this much dug out'),
  'Enclosure max tiles': lab('Land enclosed, at most (coarse tiles)'),
  'Resin per softwood tree': lab('Resin from a softwood tree'),
  'Halfling war oxen': lab('War oxen in a Halfling village'),
  'Chickens per stall': lab('Chickens in a stall'),
  'Barn stalls': lab('Stalls in a Barn'),
  'Parapet slots': lab('Men on the parapets'),
  'Parapet tier': lab('Parapets from main base tier'),
  'Cavalry base': lab('Cavalry from main base tier'),
  'Mage main base level': lab('Mages trained at a main base from tier'),
  'Mage xp rank limit': lab('Experience alone takes a mage to rank'),
  'Platform men': lab('Men on an empty engine platform'),
  'Craft pace': lab('Crafting pace with no workers'),
  'Horse upkeep': lab('A ridden horse eats a day'),
  'Facility upkeep': lab('A research building eats a day'),
  'Nutrition per cycle': lab('Each unit eats a day'),
  'Heal per xp': lab('Health healed for each experience point'),
  'Run food metres': lab('Running costs food every (metres)'),
  'Run turn': lab('A run stays straight while turning less than'),
  'Climb cost per unit': lab('Climbing weighs on a path, per step up'),
  'Home rise weight': lab('Each metre up or down counts as (metres)'),
  'Hunt picked': lab('Hunts the kind you picked'),
  'Rarity power (weight 1 / threat to this)': lab('Stronger kinds are rarer by'),
  'Keeps outside this many light radii': lab('Keeps outside lights by (times their radius)'),
  'Spots tested per side of a patch': lab('Spots tried along each side of a patch'),
  'Stroll turns at most (degrees)': lab('Turns at most (degrees)'),
  'Group grows by one every (nights)': lab('The group grows by one every (nights)'),
  'Wave gear per night': lab('Gear the waves carry, per thousand a night'),
  'Hoard rolls': lab('Rolls for the hoard'),
  'Cooked hundredths per nutrition': lab('Cooked food is worth, per 100 nutrition'),
  'Elf kingdom ring into deepwoods': lab('The Elf kingdom stands this many rings into the Deepwoods'),
  'Wander dusks': lab('A caravan leaves at dusk number'),
  'Tool kit tier with the prospecting hammer': lab('Tool kit tier with a prospecting hammer'),
  'Damage less': lab('Does this much less damage'),
  Splash: lab('Splash damage'),
  'Splash radius': lab('Splash reaches', { unit: 'metresWu' }),
  'Per ten metres': lab('Damage for every 10 m thrown'),
  'Land ds': lab('The blow lands after', { unit: 'deciseconds' }),
  Chips: lab('Chips off'),
  Fells: lab('Fells trees up to size'),
  'Curve (the 0.04n²)': lab('Grows with the night squared, times'),
  'Start (the 12)': lab('Every night starts with'),
  'Each night (the 3n)': lab('More each night, times the night'),
  'Each night after the first, extra (the n − 1)': lab('More each night after the first'),
  'Depth 1': lab('A shaft is worked out at depth 1 after'),
  'Depth 2': lab('A shaft is worked out at depth 2 after'),
  'Depth 3': lab('A shaft is worked out at depth 3 after'),
  'Damage max tenths': lab('Damage at most'),
  'Item way': lab('Ready item mark'),
  N: lab('How many'),
  Res: lab('Also gives', { ref: 'res' }),
  Alt: lab('Or instead', { ref: 'res' }),
  Scrap: lab('Scraps', { ref: 'res' }),
  Amount: lab('How many'),
  Unit: lab('Person'),
  'Building or creature': lab('Splits into'),
  Most: lab('At most'),
  Least: lab('At least'),
  Count: lab('How many'),
  Per: lab('Each'),
  Break: lab('Breaking stone'),
  Build: lab('Building'),
  Chop: lab('Chopping'),
  Cut: lab('Cutting'),
  Strike: lab('How its shot lands'),
  Ranged: lab('Ranged weapon'),
  Mount: lab('Rides'),
  Species: lab('Comes from'),
  Product: lab('Makes'),
  Guards: lab('Guards its ground within'),
  'Per cell': lab('In each stretch of land'),
  Mobile: lab('Moves'),
  Xp: lab('Experience needed'),
  'Refill (hundredths of a point a second)': lab('Mana refill a second, in hundredths'),
  'Refill in the Barrens (hundredths a second)': lab('Mana refill in the Barrens, hundredths a second'),
  'Refill near trees (hundredths a second)': lab('Mana refill near trees, hundredths a second'),
  'Shot at from a building this lately': lab('Goes for a building that shot at it within'),
  'Taming feeds an animal this much food a second': lab('Taming feeds this much food a second'),
  'Half width': lab('Body width', { unit: 'metresWu', times: 2 }),
  'Yield max': lab('Holds at most'),
  Yield: lab('Holds'),
  'Per load': lab('A load'),
  'Per night': lab('At most a night'),
  'Run food': lab('Running costs food'),
  'Raw carry': lab('Raw materials carried at most'),
  'Loot bag': lab('A loot bag holds'),
  'Dig class': lab('Digging needs'),
  Ping: lab('Pinged on the minimap'),
  Raw: lab('Counts towards the carrying limit'),
  Stack: lab('Made in stacks'),
  Turns: lab('Can be turned'),
  'Keep one': lab('Keeps one back'),
  'One attack': lab('Only while attacking'),
  Combat: lab('Needs combat experience first'),
  Ignite: lab('Sets things alight'),
  Magic: lab('A bolt of magic'),
  Cannon: lab('A gunpowder cannon'),
  Mob: lab('Monster'),
  Site: lab('Where it sits'),
  "How many wanderers (of Patch 1's)": lab('How many wanderers come out (against the first count)'),
};

/** Words on a page that read like the code: by the label the catalog gave them. */
const TEXT_LABELS: Readonly<Record<string, string>> = {
  Key: 'Hotkey', 'Blueprint row': 'Counted as', T: 'Kind of task', Tint: 'Colouring', 'Young look': 'Its young look like',
  Variants: 'Ways round', 'School names': 'Schools', Group: 'Menu', 'Called in the game': 'Named', Check: 'Comes back',
};

/** Pages whose titles are the code's: by the catalog entry. */
const TITLES: Readonly<Record<string, string>> = {
  'rules:units:units/repairs.ts': 'Repairs',
  'rules:units:units/spacing.ts': 'Making room for each other',
  'rules:animals:animals/species.ts': 'Wild animals',
  'rules:animals:buildings/data.ts': 'Barns and stalls',
  'rules:mobs:combat/mob-ai.ts': 'How monsters behave',
  'rules:mobs:combat/mobs.ts': 'Monster abilities',
  'rules:mobs:threats/data.ts': 'Fog nights',
  'rules:mobs:threats/late-mobs.ts': "Late night monsters' abilities",
  'rules:mobs:world/generate.ts': 'Where Bog guardians live',
  'rules:world:world/props.ts': 'Trees, plants and rocks',
};

/** Section headings that read like the code. */
const SECTIONS: Readonly<Record<string, string>> = {
  // Times picked anew each go, between two numbers of seconds (the code's [least, most]).
  'Wander s': 'Wanders to a new spot every',
  'Plead wander s': 'Pleading, runs to a new spot every',
  'Alarm s': 'Sounds the alarm every',
  'War line s': 'At war, speaks every',
  'Fight line s': 'In her wrath, speaks every',
  'Plant s': 'Plants a flower or fruit tree every',
  'Taunt s': 'Raging, taunts every',
  'Revel s': 'Revels every',
  'Fight s': 'Fighting, speaks every',
  'Drink s': 'Drinks every',
  'Quip s': 'Fighting, quips every',
};

/** By where the number sits, where the label alone is not enough: module, then the path with * for any index. */
const BY_PATH: Readonly<Record<string, Fix>> = {
  'units/forage.ts:FORAGE_GOODS.*.forge': lab('Forge step needed (1 any Forge; 2 to 4 its main base tier)'),
  'units/kits.ts:TIER_NEEDS.*.forge': lab('Forge step needed first (1 any Forge; 2 to 4 its main base tier)'),
  'units/woodsman.ts:WOODSMAN.damageLess': lab('Does this much less damage than a worker'),
  'threats/encounters.ts:ENCOUNTERS.silenus.lash.m': lab('Lash reaches', M),
  'threats/encounters.ts:ENCOUNTERS.ape.goods.fruit': lab('Fruit he gives'),
  'threats/encounters.ts:ENCOUNTERS.ape.goods.honey': lab('Honey he gives'),
  'threats/encounters.ts:ENCOUNTERS.ape.goods.wine': lab('Enchanted wine he gives'),
  'threats/encounters.ts:ENCOUNTERS.lich.grave.floor': lab('Health it never takes below'),
  'threats/late-mobs.ts:LATE.rift.every': lab('Brings one through every', { unit: 'seconds' }),
  'threats/late-mobs.ts:LATE.rift.open': lab('Stays open for', { unit: 'seconds' }),
  'threats/late-mobs.ts:LATE.ruin.warning': lab('Warns for', { unit: 'seconds' }),
  'threats/late-mobs.ts:LATE.blink.distance': lab('Blinks up to', { unit: 'metresWu' }),
  'threats/late-mobs.ts:LATE.blink.threat': lab('Picks a target within', { unit: 'metresWu' }),
  'threats/late-mobs.ts:LATE.raise.within': lab('Raises the dead within', { unit: 'metresWu' }),
  'threats/late-mobs.ts:LATE.line.width': lab('Width', { unit: 'metresWu' }),
  'threats/encounters.ts:ENCOUNTERS.ape.toss.metresPerSecond': lab('Flies through the air at (metres a second)'),
  'combat/blasts.ts:CRATER.columns': lab('A crater reaches out', COL),
  'combat/blasts.ts:CRATER.middle': lab('A crater is this deep in the middle', TU),
  'combat/blasts.ts:CRATER.edge': lab('A crater is this deep at its edge', TU),
  'combat/mobs.ts:CLUSTER.units': lab('Units in a cluster'),
  'magic/mages.ts:CRYSTAL_STAND_IN.per': lab('Mana crystals stand in for each'),
  'circles/data.ts:CHEST_LOOT.*.count': lab('How many'),
};

/** The code's own bookkeeping, not a number of the game: kept off the pages (but counted as shown). */
const INTERNAL: ReadonlySet<string> = new Set([
  'world/props.ts:ALL_JOBS', 'world/props.ts:TOOL_JOBS', 'nav/grid.ts:NO_FLOOR', 'nav/grid.ts:TOP', 'nav/grid.ts:UNDER',
  'state.ts:VISION_STRIDE', 'state.ts:PEOPLES', 'units/questions.ts:QUESTION_FOREVER', 'units/kits.ts:ITEM_WAY',
  'world/materials.ts:MATERIALS.*.colour', 'units/spacing.ts:SPACING_SCAN', 'units/spacing.ts:SPACING_NEIGHBOURS',
  'units/spacing.ts:SPACING_SLACK_WU', 'units/spacing.ts:SPREAD_PULL_PM', 'units/repairs.ts:AUTO_REPAIR_EVERY',
  'buildings/farm-boost.ts:FARM_PACE', 'combat/projectiles.ts:GRAVITY', 'units/greyed.ts:GREY_DEPTH',
]);

/** A page's words without the design's bookkeeping: table references, the editor's asides, name templates. */
export function plainText(label: string, text: string): string {
  if (/^Worked out in code/.test(text)) {
    if (label === 'Sleepers') return 'Its sleepers change with the nights: more of them, and stronger kinds, as the nights go on.';
    text = text.replace(/^Worked out in code[.:]?\s*/, '').replace(/\s*Ask for a change in a note\.$/, '');
  }
  return text
    .replace(/\s*\((?:Table|Tables) [^)]*\)/g, '')
    .replace(/\{Name\}/g, '(its name)')
    .trim();
}

/** The key a field is found by: "module:EXPORT.*.key". */
const keyOf = (f: FieldNode): string => `${f.module}:${f.path.map((p) => (typeof p === 'number' ? '*' : p)).join('.')}`;

/** Labels that only identify a row to the code, wherever they show. */
const INTERNAL_LABELS: ReadonlySet<string> = new Set(['Id', 'Kind', 'Shape', 'Stage', 'State', 'Prop']);

/** Whether a field is the code's bookkeeping, to leave off the pages. */
export function isInternal(f: FieldNode): boolean {
  return INTERNAL.has(keyOf(f)) || INTERNAL_LABELS.has(f.label);
}

/** Gives the catalog's numbers plain names and the units they are in. Changes the catalog in place (How to Play's own copy). */
export function plainWords(cat: Catalog): void {
  const done = new WeakSet<FieldNode>();
  const fixField = (f: FieldNode): void => {
    if (done.has(f)) return;
    done.add(f);
    const fix = BY_PATH[keyOf(f)] ?? BY_LABEL[f.label];
    if (!fix) return;
    const mut = f as { label: string; unit: UnitId; value: number | boolean; ref?: RefKind };
    if (fix.label) mut.label = fix.label;
    if (fix.ref && !f.ref) mut.ref = fix.ref;
    if (fix.unit) {
      mut.unit = fix.unit;
      if (fix.times && typeof f.value === 'number') mut.value = f.value * fix.times;
    }
  };
  const walk = (nodes: readonly CatNode[]): void => {
    for (const n of nodes) {
      if (n.type === 'field') fixField(n);
      else if (n.type === 'pair') fixField(n.amount);
      else if (n.type === 'text') {
        const t = n as { label: string; text: string };
        t.text = plainText(t.label, t.text);
        t.label = TEXT_LABELS[t.label] ?? t.label;
      } else {
        const sec = n as { label: string; children: readonly CatNode[] };
        const [lo, hi] = sec.children;
        // A [least, most] pair of seconds reads "1" and "2" in the catalog.
        if (/ s$/.test(sec.label) && sec.children.length === 2 && lo?.type === 'field' && hi?.type === 'field' && lo.label === '1' && hi.label === '2') {
          for (const [f, label] of [[lo, 'At least'], [hi, 'At most']] as const) {
            done.add(f);
            Object.assign(f, { label, unit: S.unit });
          }
        }
        sec.label = SECTIONS[sec.label] ?? sec.label.charAt(0).toUpperCase() + sec.label.slice(1);
        walk(sec.children);
      }
    }
  };
  // Every page's tree, and the flat list of fields (a few rules pages hold their own copies of a field).
  for (const e of cat.entries.values()) {
    const title = TITLES[e.id];
    if (title) (e as { label: string }).label = title;
    walk(e.children);
  }
  for (const f of cat.fields.values()) fixField(f);
}
